---
# defaults file for nodejs
- hosts: tag_Name_bastion_instance
  remote_user: ubuntu
  become: yes
  gather_facts: False
  vars:
    - homeDir: /home/ubuntu
    - appDir : app
    - repo: my_app

  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - name: Install Packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - npm
        - nodejs-legacy
        - git
        - nginx
  
    - name: Install express
      npm: name=express global=yes production=yes
    - name: Install pm2
      npm: name=pm2 global=yes production=yes

    - copy:
        src: ../application/
        dest: "{{homeDir}}/{{appDir}}"
    - name: Running NPM install
      npm: path={{homeDir}}/{{appDir}}

    - name: Start APP
      command: pm2 start server.js --name app chdir={{homeDir}}/{{appDir}}
      ignore_errors: yes
  